server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

memberlist:
  join_members: []  # Mantém vazio se não há outros nós

schema_config:
  configs:
    - from: 2021-08-01
      store: tsdb
      object_store: filesystem  # Use filesystem se não estiver usando S3
      schema: v13
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    filesystem:  # Configuração para armazenamento local
      directory: /loki/storage
  ring:
    kvstore:
      store: memberlist

ruler:
  storage:
    filesystem:  # Configuração para armazenamento local
      directory: /loki/ruler

compactor:
  working_directory: /tmp/compactor
