version: '3.8'

services:
  loki:
    build:
      context: ./loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/etc/loki
    networks:
      - logging-network

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "changeme"
    depends_on:
      - loki
    networks:
      - logging-network

  promtail:
    build:
      context: ./promtail
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    volumes:
      - /var/log:/var/log
    depends_on:
      - loki
    networks:
      - logging-network

volumes:
  loki_data:

networks:
  logging-network:
    driver: bridge
