version: 1
services:
  - type: web
    name: grafana
    runtime: docker
    plan: free
    envVars:
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: "admin"
    buildCommand: ""
    startCommand: ""

  - type: web
    name: promtail
    runtime: docker
    plan: free
    envVars:
      - key: LOKI_ADDR
        value: "http://loki:3100/loki/api/v1/push"
    buildCommand: ""
    startCommand: ""
