version: 1
services:
  - type: web
    name: grafana
    runtime: docker
    plan: free
    envVars:
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: "admin"
    env:
      - key: RENDER_EXTERNAL_HOSTNAME
        value: grafana

  - type: web
    name: promtail
    runtime: docker
    plan: free
    envVars:
      - key: LOKI_ADDR
        value: "http://loki:3100/loki/api/v1/push"
    env:
      - key: RENDER_EXTERNAL_HOSTNAME
        value: promtail
