version: 1
services:
  - type: web
    name: grafana
    runtime: docker
    plan: free
    envVars:
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: "admin"
    buildCommand: ./grafana
    startCommand: grafana-server --config=/etc/grafana/grafana.ini

  - type: web
    name: promtail
    runtime: docker
    plan: free
    envVars:
      - key: LOKI_ADDR
        value: "http://loki:3100/loki/api/v1/push"
    buildCommand: ./promtail
    startCommand: promtail -config.file=/etc/promtail/promtail-config.yml
