version: 1
services:
  - type: web
    name: grafana
    runtime: docker
    plan: free
    envVars:
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: "admin"
    dockerfilePath: grafana/Dockerfile
    envVars:
      - key: GF_PATHS_CONFIG
        value: "/etc/grafana/grafana.ini"

  - type: web
    name: promtail
    runtime: docker
    plan: free
    envVars:
      - key: LOKI_ADDR
        value: "http://loki:3100/loki/api/v1/push"
    dockerfilePath: promtail/Dockerfile
