server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /mnt/data/promtail_positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: 'prod-server'
          __path__: /var/log/**/*.log
